# Generated by Django 4.2.1 on 2024-02-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travelapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Men",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_men", models.CharField(max_length=250)),
                ("img_men", models.ImageField(upload_to="pics")),
                ("desc_men", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="place",
            name="name",
            field=models.CharField(max_length=250),
        ),
    ]
